### ISSUE TITLE
No supported formats (Available formats: lcpl)

### ISSUE THREAD

**Issue by Spaskich** [Leseratte10/lcpl-calibre-plugin#4]
### Bug description

I installed the plugin, but when trying to convert the .lcpl file, I get the following error:
```
calibre, version 6.3.0
WARNING: Could not convert some books: Could not convert the book because no supported source format was found

license - No supported formats (Available formats: lcpl)
```
license is the filename I'm trying to convert - license.lcpl
I've tried restarting after installing the plugin, reinstalling it, etc.

### Operating system

Windows

### Which version of Calibre are you running?

6.3.0

### Which version of the LCPL Input plugin are you running?

v0.0.5

**Comment by Leseratte10** [comment]
This plugin isn't a conversion plugin, it's a file type plugin. The plugin only runs when you import an LCPL file into Calibre, not when trying to convert it. I assume you first added the LCPL file and then installed this plugin?

Remove the LCPL file from the library then import it again and then it should turn into an EPUB (or PDF) automatically. If not, please post a debug log from the import attempt, not the conversion attempt.

**Comment by Spaskich** [comment]
Yes, this was the exact reason, that's why I closed the issue.
